services:
  stackexchange.api:
    image: stackexchange.api
    build:
      context: .
      dockerfile: StackExchange.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  
  stackexchange.database:
    image: postgres:latest
    container_name: stackexchange.database
    environment:
      - POSTGRES_DB=tag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/stackexchange-db:/var/lib/postgresql/data
    ports:
      - 5432:5432