services:
  stackexchange.api:
    image: stackexchange.api
    build:
      context: .
      dockerfile: StackExchange.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      stackexchange.database:
        condition: service_healthy
    restart: always
  
  stackexchange.database:
    image: postgres:latest
    container_name: stackexchange.database
    environment:
      - POSTGRES_DB=tag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/stackexchange-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

