@StackExchange.API_HostAddress = http://localhost:8080

GET {{StackExchange.API_HostAddress}}/test/
Accept: application/json

###

GET {{StackExchange.API_HostAddress}}/tags?count=325

###
GET {{StackExchange.API_HostAddress}}/tags?count=40&pageSize=100

###
GET {{StackExchange.API_HostAddress}}/result
###
###http://localhost:8080/tags?count=14&pageSize=1002